1720642786.5:  Executing midas2 subcommand annotate_genome.
1720642786.5:  Annotating genome ASM1796111v1.PrevotellaS2 from species 100003.
Traceback (most recent call last):
  File "/home/users/elisevl/mambaforge/envs/midas2/bin/midas2", line 8, in <module>
    sys.exit(main())
  File "/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/site-packages/midas2/__main__.py", line 24, in main
    return subcommand_main(subcommand_args)
  File "/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/site-packages/midas2/subcommands/annotate_genome.py", line 189, in main
    annotate_genome(args)
  File "/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/site-packages/midas2/subcommands/annotate_genome.py", line 56, in annotate_genome
    annotate_genome_master(args)
  File "/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/site-packages/midas2/subcommands/annotate_genome.py", line 122, in annotate_genome_master
    multithreading_map(genome_work, genome_id_list, num_threads=num_physical_cores)
  File "/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/site-packages/midas2/common/utils.py", line 540, in multithreading_map
    return _multi_map(func, items, num_threads, ThreadPool)
  File "/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/site-packages/midas2/common/utils.py", line 520, in _multi_map
    return p.map(func, items, chunksize=1)
  File "/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/site-packages/midas2/subcommands/annotate_genome.py", line 105, in genome_work
    command(worker_cmd)
  File "/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/site-packages/midas2/common/utils.py", line 246, in command
    return subprocess.run(cmd, shell=shell, **subproc_args)
  File "/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd /scratch/users/elisevl/Temporary-Database/midas2_protocol/midasdb_custom/gene_annotations/100003/ASM1796111v1.PrevotellaS2; PYTHONPATH=/home/users/elisevl/mambaforge/envs/midas2/lib/python3.8/site-packages /home/users/elisevl/mambaforge/envs/midas2/bin/python -m midas2 annotate_genome --genome ASM1796111v1.PrevotellaS2 --zzz_worker_mode --midasdb_name newdb --midasdb_dir /scratch/users/elisevl/Temporary-Database/midas2_protocol/midasdb_custom --debug  &>> /scratch/users/elisevl/Temporary-Database/midas2_protocol/midasdb_custom/gene_annotations/100003/ASM1796111v1.PrevotellaS2/annotate_genome.log' returned non-zero exit status 1.
